<!DOCTYPE html>
<!--
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.0
Version: 1.5.2
Author: KeenThemes
Website: http://www.keenthemes.com/
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
-->
<!--[if IE 8]>
<html lang="zh" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="zh" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="zh" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8"/>
    <title>听课数据收集反馈系统</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <meta name="MobileOptimized" content="320">
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
    <link href="/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/fullcalendar/fullcalendar/fullcalendar.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/jqvmap/jqvmap/jqvmap.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css"/>
    <!-- END PAGE LEVEL PLUGIN STYLES -->
    <!-- BEGIN THEME STYLES -->
    <link href="/assets/css/style-metronic.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/style.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/plugins.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/pages/tasks.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
    <link href="/assets/css/custom.css" rel="stylesheet" type="text/css"/>
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="favicon.ico"/>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed">
<!-- BEGIN HEADER -->
<div class="header navbar navbar-inverse navbar-fixed-top">
    <!-- BEGIN TOP NAVIGATION BAR -->
    <div class="header-inner">
        <!-- BEGIN LOGO -->
        <a class="navbar-brand" href="/index.php?a=main">
            <span class="img-responsive">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;听课数据收集反馈系统</span>
        </a>
        <!-- END LOGO -->
        <!-- BEGIN TOP NAVIGATION MENU -->
        <ul class="nav navbar-nav pull-right">
            <!-- BEGIN USER LOGIN DROPDOWN -->
            <li class="dropdown user">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                   data-close-others="true">
                    <span class="username">您好,<?php echo $user['username']; ?>老师!!</span>
                    <i class="icon-angle-down"></i>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/index.php?a=main"><i class="icon-user"></i> 个人资料</a></li>
                    <li><a href="/index.php?a=changepassword"><i class="icon-tasks"></i> 修改密码</a></li>
                    <li class="divider"></li>
                    <li><a href="javascript:;" id="trigger_fullscreen"><i class="icon-move"></i> 全屏</a>
                    </li>

                    <li><a href="/index.php?a=logout"><i class="icon-key"></i> 注销</a>
                    </li>
                </ul>
            </li>
            <!-- END USER LOGIN DROPDOWN -->
        </ul>
        <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END TOP NAVIGATION BAR -->
</div>
<!-- END HEADER -->
<div class="clearfix"></div>
<!-- BEGIN CONTAINER -->
<div class="page-container">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar navbar-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <ul class="page-sidebar-menu">
            <li>
                <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                <div class="sidebar-toggler hidden-phone"></div>
                <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
            </li>
            <li>
                <div style="height: 20px">
                </div>
            </li>
            <li class="start">
                <a href="/index.php?a=main">
                    <i class="icon-home"></i>
                    <span class="title">主页</span>
                </a>
            </li>
            <li class="">
                <a href="/index.php?a=addinfo">
                    <i class=" icon-plus-sign"></i>
                    <span class="title">添加记录</span>
                </a>
            </li>
            <li class="">
                <a href="javascript:;">
                    <i class="icon-book"></i>
                    <span class="title">查看记录</span>
                    <span class="arrow "></span>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a href="/index.php?a=listall">
                            全部记录</a>
                    </li>
                    <li>
                        <a href="/index.php?a=listpush">
                            已提交</a>
                    </li>
                    <li>
                        <a href="/index.php?a=listnotpush">
                            未提交</a>
                    </li>
                </ul>
            </li>
            <li class="">
                <a href="/index.php?a=listteacher">
                    <i class=" icon-envelope"></i>
                    <span class="title">教师评价</span>
                </a>
            </li>
            <li class="">
                <a href="/index.php?a=listteach">
                    <i class="  icon-comments"></i>
                    <span class="title">教学建议</span>
                </a>
            </li>

            <?php if($pclasses || $class){ ?>
                <li class="">
                    <a href="javascript:;">
                        <i class="icon-th-large"></i>
                        <span class="title">班级管理</span>
                        <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <?php foreach($pclasses as $pclass){ ?>
                            <li>
                                <a href="/index.php?c=pioneer&cid=<?php echo $pclass['cid'] ?>">
                                    <?php echo $pclass['cid'] ?></a>
                            </li>
                        <?php } ?>
                        <?php if($hclass){ ?>
                            <li>
                                <a href="/index.php?c=head&cid=<?php echo $hclass['cid'] ?>">
                                    <?php echo $hclass['cid'] ?></a>
                            </li>
                        <?php } ?>
                    </ul>
                </li>

            <?php } ?>

            <?php if($pclasses || $user['isadmin']=='1'){ ?>
                <li class="">
                    <a href="javascript:;">
                        <i class="icon-search"></i>
                        <span class="title">查阅记录</span>
                        <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="/index.php?c=search&a=majorlist">
                                按专业查阅</a>
                        </li>
                        <li>
                            <a href="/index.php?c=search&a=gradelist">
                                按年级查阅</a>
                        </li>
                        <li>
                            <a href="/index.php?c=search&a=classlist">
                                按班级查阅</a>
                        </li>
                    </ul>
                </li>

            <?php } ?>
            <?php if($user['isadmin']=='1'){ ?>
                <li class="">
                    <a href="javascript:;">
                        <i class="icon-bar-chart"></i>
                        <span class="title">查看统计</span>
                        <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="/index.php?c=manage&a=classes">
                                班级统计</a>
                        </li>
                        <li>
                            <a href="/index.php?c=manage&a=teacher">
                                教师统计</a>
                        </li>
                        <li>
                            <a href="#">
                                系统抽查</a>
                        </li>
                    </ul>
                </li>
                <li class="">
                    <a href="javascript:;">
                        <i class="icon-cogs"></i>
                        <span class="title">系统管理</span>
                        <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="/index.php?c=manage&a=mcollege">
                                学院管理</a>
                        </li>
                        <li>
                            <a href="/index.php?c=manage&a=mclassroom">
                                教室管理</a>
                        </li>
                        <li>
                            <a href="/index.php?c=manage&a=mteacher">
                                教师管理</a>
                        </li>
                        <li>
                            <a href="/index.php?c=manage&a=mmajor">
                                专业管理</a>
                        </li>
                        <li>
                            <a href="/index.php?c=manage&a=mclass">
                                班级管理</a>
                        </li>
                    </ul>
                </li>

            <?php } ?>
            <li class="last ">
                <a href="">
                    <i class="icon-edit"></i>
                    <span class="title">用户反馈</span>
                </a>
            </li>
        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
    <!-- BEGIN PAGE -->
    <div class="page-content">
        <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
        <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title">Modal title</h4>
                    </div>
                    <div class="modal-body">
                        Widget settings form goes here
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn blue">Save changes</button>
                        <button type="button" class="btn default" data-dismiss="modal">Close</button>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
        <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->

        <!-- BEGIN PAGE HEADER-->
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN PAGE TITLE & BREADCRUMB-->

                <ul class="page-breadcrumb breadcrumb">
                    <li>
                        <i class="icon-user-md"></i>
                        <a href="#">管理员</a>
                        <i class="icon-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">查阅记录</a>
                        <i class="icon-angle-right"></i>
                    </li>
                    <li><a href="#">按专业查阅</a></li>
                    <li class="pull-right">
                        <div id="dashboard-report-range" class="dashboard-date-range tooltips" >
                            <i class="icon-calendar"></i>
                            <span><?php echo date('Y年m月d日 ',time());  $weeks=array('周日','周一','周二','周三','周四','周五','周六');echo $weeks[date('w',time())+0]; ?></span>
                        </div>
                    </li>
                </ul>
                <!-- END PAGE TITLE & BREADCRUMB-->
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN SAMPLE TABLE PORTLET-->
                <div class="portlet box red">
                    <div class="portlet-title">
                        <div class="caption"><i class="icon-book" style="font-size: 18px"></i>专业</div>

                    </div>
                    <div class="portlet-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr style="text-align: center">
                                    <th>时间</th>
                                    <th>课程</th>
                                    <th>教室</th>
                                    <th>授课教师</th>
                                    <th>听课教师</th>
                                    <th>操作</th>
                                </tr>
                                </thead>
                                <tbody>

                                <?php foreach($attends as $attend) { ?>
                                    <tr>
                                        <td><?php echo $attend['time'] ?></td>
                                        <td><?php echo $attend['classname'] ?></td>
                                        <td><?php echo $attend['classroom'] ?></td>
                                        <td><?php echo $attend['tname'] ?></td>
                                        <td><?php echo $attend['aname'] ?></td>
                                        <td>
                                            <a href="/index.php?c=search&a=browse&aid=<?php echo $attend['id'] ?>">
                                                <button type="button" class="btn yellow btn-xs">
                                                    <i class="icon-search"></i>
                                                    <span class="title">查看</span>
                                                </button>
                                            </a>

                                        </td>

                                    </tr>

                                <?php } ?>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- END SAMPLE TABLE PORTLET-->

            </div>
        </div>

    </div>
    <!-- END PAGE -->
</div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
<div class="footer">
    <div class="footer-inner">
        2013 &copy; Metronic by keenthemes.
    </div>
    <div class="footer-tools">
         <span class="go-top">
         <i class="icon-angle-up"></i>
         </span>
    </div>
</div>
<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="/assets/plugins/respond.min.js"></script>
<script src="/assets/plugins/excanvas.min.js"></script>
<![endif]-->
<script src="/assets/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
<!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
<script src="/assets/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
<script src="/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="/assets/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js"
        type="text/javascript"></script>
<script src="/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery.cookie.min.js" type="text/javascript"></script>
<script src="/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="/assets/plugins/jqvmap/jqvmap/jquery.vmap.js" type="text/javascript"></script>
<script src="/assets/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js" type="text/javascript"></script>
<script src="/assets/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js" type="text/javascript"></script>
<script src="/assets/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js" type="text/javascript"></script>
<script src="/assets/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js" type="text/javascript"></script>
<script src="/assets/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js" type="text/javascript"></script>
<script src="/assets/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js" type="text/javascript"></script>
<script src="/assets/plugins/flot/jquery.flot.js" type="text/javascript"></script>
<script src="/assets/plugins/flot/jquery.flot.resize.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery.pulsate.min.js" type="text/javascript"></script>
<script src="/assets/plugins/bootstrap-daterangepicker/moment.min.js" type="text/javascript"></script>
<script src="/assets/plugins/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>
<!-- IMPORTANT! fullcalendar depends on jquery-ui-1.10.3.custom.min.js for drag & drop support -->
<script src="/assets/plugins/fullcalendar/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.js" type="text/javascript"></script>
<script src="/assets/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="/assets/scripts/app.js" type="text/javascript"></script>
<script src="/assets/scripts/index.js" type="text/javascript"></script>
<script src="/assets/scripts/tasks.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
    jQuery(document).ready(function () {
        App.init(); // initlayout and core plugins
        Index.init();
        Index.initJQVMAP(); // init index page's custom scripts
        Index.initCalendar(); // init index page's custom scripts
        Index.initCharts(); // init index page's custom scripts
        Index.initChat();
        Index.initMiniCharts();
        Index.initDashboardDaterange();
        Index.initIntro();
        Tasks.initDashboardWidget();
    });
</script>
<!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>