<!DOCTYPE html>
<!--
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.0
Version: 1.5.2
Author: KeenThemes
Website: http://www.keenthemes.com/
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
-->
<!--[if IE 8]>
<html lang="zh" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]>
<html lang="zh" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="zh" class="no-js"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8"/>
    <title>听课数据收集反馈系统</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <meta name="MobileOptimized" content="320">
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
    <link href="/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/fullcalendar/fullcalendar/fullcalendar.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/jqvmap/jqvmap/jqvmap.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css"/>
    <!-- END PAGE LEVEL PLUGIN STYLES -->
    <!-- BEGIN THEME STYLES -->
    <link href="/assets/css/style-metronic.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/style.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/plugins.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/pages/tasks.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
    <link href="/assets/css/custom.css" rel="stylesheet" type="text/css"/>
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="favicon.ico"/>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body class="page-header-fixed">
<!-- BEGIN HEADER -->
<div class="header navbar navbar-inverse navbar-fixed-top">
    <!-- BEGIN TOP NAVIGATION BAR -->
    <div class="header-inner">
        <!-- BEGIN LOGO -->
        <a class="navbar-brand" href="/index.php">
            <span class="img-responsive">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;听课数据收集反馈系统</span>
        </a>
        <!-- END LOGO -->
        <!-- BEGIN TOP NAVIGATION MENU -->
        <ul class="nav navbar-nav pull-right">
            <!-- BEGIN USER LOGIN DROPDOWN -->
            <li class="dropdown user">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown"
                   data-close-others="true">
                    <span class="username">您好,<?php echo $user['username']; ?>老师!!</span>
                    <i class="icon-angle-down"></i>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/index.php?a=person"><i class="icon-user"></i> 个人资料</a></li>
                    <li><a href="/index.php?a=changepassword"><i class="icon-tasks"></i> 修改密码</a></li>
                    <li class="divider"></li>
                    <li><a href="javascript:;" id="trigger_fullscreen"><i class="icon-move"></i> 全屏</a>
                    </li>

                    <li><a href="/index.php?a=logout"><i class="icon-key"></i> 注销</a>
                    </li>
                </ul>
            </li>
            <!-- END USER LOGIN DROPDOWN -->
        </ul>
        <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END TOP NAVIGATION BAR -->
</div>
<!-- END HEADER -->
<div class="clearfix"></div>
<!-- BEGIN CONTAINER -->
<div class="page-container">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar navbar-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <ul class="page-sidebar-menu">
            <li>
                <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                <div class="sidebar-toggler hidden-phone"></div>
                <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
            </li>
            <li>
                <div style="height: 20px">
                </div>
            </li>
            <li class="start  ">
                <a href="/index.php">
                    <i class="icon-home"></i>
                    <span class="title">主页</span>
                </a>
            </li>
            <li class="">
                <a href="/index.php?a=addinfo">
                    <i class=" icon-plus-sign"></i>
                    <span class="title">添加记录</span>
                </a>
            </li>
            <li class="">
                <a href="javascript:;">
                    <i class="icon-book"></i>
                    <span class="title">查看记录</span>
                    <span class="arrow "></span>
                </a>
                <ul class="sub-menu">
                    <li>
                        <a href="/index.php?a=listall">
                            全部记录</a>
                    </li>
                    <li>
                        <a href="/index.php?a=listpush">
                            已提交</a>
                    </li>
                    <li>
                        <a href="/index.php?a=listnotpush">
                            未提交</a>
                    </li>
                </ul>
            </li>
            <li class="">
                <a href="/index.php?a=listteacher">
                    <i class=" icon-envelope"></i>
                    <span class="title">教师评价</span>
                </a>
            </li>
            <li class="">
                <a href="/index.php?a=listteach">
                    <i class="  icon-comments"></i>
                    <span class="title">教学建议</span>
                </a>
            </li>

            <?php if($pclasses || $hclass){ ?>
                <li class="">
                    <a href="javascript:;">
                        <i class="icon-th-large"></i>
                        <span class="title">班级管理</span>
                        <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <?php foreach($pclasses as $pclass){ ?>
                            <li>
                                <a href="/index.php?c=pioneer&cid=<?php echo $pclass['cid'] ?>">
                                    <?php echo $pclass['cid'] ?></a>
                            </li>
                        <?php } ?>
                        <?php if($hclass){ ?>
                            <li>
                                <a href="/index.php?c=head&cid=<?php echo $hclass['cid'] ?>">
                                    <?php echo $hclass['cid'] ?></a>
                            </li>
                        <?php } ?>
                    </ul>
                </li>

            <?php } ?>

            <?php if($pclasses || $user['isadmin']=='1'){ ?>
                <li class="">
                    <a href="javascript:;">
                        <i class="icon-search"></i>
                        <span class="title">查阅记录</span>
                        <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="/index.php?c=search&a=majorlist">
                                按专业查阅</a>
                        </li>
                        <li>
                            <a href="/index.php?c=search&a=gradelist">
                                按年级查阅</a>
                        </li>
                        <li>
                            <a href="/index.php?c=search&a=classlist">
                                按班级查阅</a>
                        </li>
                    </ul>
                </li>

            <?php } ?>
            <?php if($user['isadmin']=='1'){ ?>
                <li class="">
                    <a href="javascript:;">
                        <i class="icon-bar-chart"></i>
                        <span class="title">查看统计</span>
                        <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="/index.php?c=manage&a=classes">
                                班级统计</a>
                        </li>
                        <li>
                            <a href="/index.php?c=manage&a=teacher">
                                教师统计</a>
                        </li>
                        <li>
                            <a href="/index.php?c=manage&a=check">
                                系统抽查</a>
                        </li>
                    </ul>
                </li>
                <li class="">
                    <a href="javascript:;">
                        <i class="icon-cogs"></i>
                        <span class="title">系统管理</span>
                        <span class="arrow "></span>
                    </a>
                    <ul class="sub-menu">
                        <li>
                            <a href="/index.php?c=manage&a=mcollege">
                                学院管理</a>
                        </li>
                        <li>
                            <a href="/index.php?c=manage&a=mclassroom">
                                教室管理</a>
                        </li>
                        <li>
                            <a href="/index.php?c=manage&a=mteacher">
                                教师管理</a>
                        </li>
                        <li>
                            <a href="/index.php?c=manage&a=mmajor">
                                专业管理</a>
                        </li>
                        <li>
                            <a href="/index.php?c=manage&a=mclass">
                                班级管理</a>
                        </li>
                    </ul>
                </li>
                <li class="">
                    <a href="/index.php?c=manage&a=mback">
                        <i class=" icon-envelope"></i>
                        <span class="title">下载备份</span>
                    </a>
                </li>
                <li class="">
                    <a href="/index.php?c=manage&a=mclear">
                        <i class=" icon-envelope"></i>
                        <span class="title">清除数据</span>
                    </a>
                </li>

            <?php } ?>
            <li class="last ">
                <a href="">
                    <i class="icon-edit"></i>
                    <span class="title">用户反馈</span>
                </a>
            </li>
        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
    <!-- BEGIN PAGE -->
    <div class="page-content">
        <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
        <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title">Modal title</h4>
                    </div>
                    <div class="modal-body">
                        Widget settings form goes here
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn blue">Save changes</button>
                        <button type="button" class="btn default" data-dismiss="modal">Close</button>
                    </div>
                </div>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
        <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->

        <!-- BEGIN PAGE HEADER-->
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN PAGE TITLE & BREADCRUMB-->

                <ul class="page-breadcrumb breadcrumb">
                    <li>
                        <i class="icon-home"></i>
                        <a href="#">教师</a>
                        <i class="icon-angle-right"></i>
                    </li>
                    <li><a href="#">添加记录</a></li>
                    <li class="pull-right">
                        <div id="dashboard-report-range" class="dashboard-date-range tooltips" >
                            <i class="icon-calendar"></i>
                            <span><?php echo date('Y年m月d日 ',time());  $weeks=array('周日','周一','周二','周三','周四','周五','周六');echo $weeks[date('w',time())+0]; ?></span>
                        </div>
                    </li>
                </ul>
                <!-- END PAGE TITLE & BREADCRUMB-->
            </div>
        </div>
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTAINER-->
        <div class="row">
            <div class="col-md-12">
                <div class="portlet box blue" id="form_wizard_1">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-reorder"></i> 添加听课记录
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <form novalidate="novalidate" action="/index.php?a=doattend" method="post" class="form-horizontal" id="submit_form">
                            <div class="form-wizard">
                                <div class="form-body">
                                    <ul class="nav nav-pills nav-justified steps">
                                        <li class="done">
                                            <a href="/index.php?a=addinfo" class="step">
                                                <span class="number">1</span>
                                                <span class="desc"><i class="icon-ok"></i> 课程信息</span>
                                            </a>
                                        </li">
                                        <li  class="active ">
                                            <a href="/index.php?a=addattend" class="step">
                                                <span class="number">2</span>
                                                <span class="desc"><i class="icon-ok"></i> 听课情况</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/index.php?a=addsug" class="step active">
                                                <span class="number">3</span>
                                                <span class="desc"><i class="icon-ok"></i> 建议评价</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="/index.php?a=addphoto" class="step">
                                                <span class="number">4</span>
                                                <span class="desc"><i class="icon-ok"></i> 附件上传</span>
                                            </a>
                                        </li>
                                    </ul>
                                    <div id="bar" class="progress progress-striped" role="progressbar">
                                        <div style="width: 50%;" class="progress-bar progress-bar-success"></div>
                                    </div>
                                    <div class="tab-content">
                                        <div style="display: none;" class="alert alert-success display-none">
                                            <button class="close" data-dismiss="alert"></button>
                                        </div>
                                        <div class="tab-pane active" id="tab1">
                                            <div class="form-group ">
                                            <h4 class="col-md-offset-2 col-md-3">教师工作情况</h4></div>
                                            <div class="form-group ">
                                                <label class="control-label col-md-3">迟到时间</label>
                                                <div class="col-md-4">
                                                    <select name="latetime" required=""  class="form-control form-control-inline input-medium">
                                                        <?php for($i=0;$i<10;$i++){ ?>
                                                            <option value="<?php echo $i;?>" <?php if($attend['latetime']==$i) echo 'selected'; ?>><?php echo $i;?></option>
                                                        <?php } ?>
                                                    </select>分钟
                                                </div>
                                            </div>
                                            <div class="form-group ">
                                                <label class="control-label col-md-3">早退时间</label>
                                                <div class="col-md-4">
                                                    <select name="earlytime" required=""  class="form-control form-control-inline input-medium">
                                                        <?php for($i=0;$i<10;$i++){ ?>
                                                            <option value="<?php echo $i;?>" <?php if($attend['earlytime']==$i) echo 'selected'; ?>><?php echo $i;?></option>
                                                        <?php } ?>
                                                    </select>分钟
                                                </div>
                                            </div>

                                            <div class="form-group ">
                                                <label class="control-label col-md-3">其他违纪情况</label>
                                                <div class="col-md-4">
                                                    <textarea name="other" class="form-control" rows="3"><?php echo $attend["other"]; ?></textarea>
                                                </div>
                                            </div>
                                            <div class="form-group ">
                                                <h4 class="col-md-offset-2 col-md-3">学生情况</h4></div>
                                            <div class="form-group ">
                                                <label class="control-label col-md-3">应到人数</label>
                                                <div class="col-md-4">
                                                    <input name="stunum" readonly class="form-control form-control-inline input-medium" size="16" value="<?php echo $stunum[0];?>" type="text">

                                                </div>
                                            </div>
                                            <div class="form-group ">
                                                <label class="control-label col-md-3">实到人数</label>
                                                <div class="col-md-4">
                                                    <input name="comenum" class="form-control form-control-inline input-medium" size="16" value="<?php echo $attend["comenum"]; ?>" type="text">
                                                </div>
                                            </div>
                                            <div class="form-group ">
                                                <label class="control-label col-md-3">迟到人数</label>
                                                <div class="col-md-4">
                                                    <input name="latenum" class="form-control form-control-inline input-medium" size="16" value="<?php echo $attend["latenum"]; ?>" type="text">
                                                </div>
                                            </div>
                                            <div class="form-group ">
                                                <h4 class="col-md-offset-2 col-md-3">教师课堂评价指标</h4></div>
                                            <div class="form-group">
                                                <?php $assess = array(); for($i = 0 ;$i<11;$i++){$assess[$i]=0;}?>
                                                <label class="col-md-3 control-label">1.讲课有热情,精神饱满</label>
                                                <div class="col-md-9">
                                                    <div class="radio-list">
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess1" id="assess11" value="A" <?php if($attend['assess1']=='A'){echo 'checked'; $assess[1]=95;} ?> type="radio" onclick="window.assess[0]=95;avassess()">
                                                                </span>
                                                            </div>
                                                            A
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess1" id="assess12" value="B" <?php if($attend['assess1']=='B'){echo 'checked'; $assess[1]=85;} ?> type="radio" onclick="window.assess[0]=85;avassess()">
                                                                </span>
                                                            </div>
                                                            B
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess1" id="assess13" value="C" <?php if($attend['assess1']=='C'){echo 'checked'; $assess[1]=75;} ?>  type="radio" onclick="window.assess[0]=75;avassess()">
                                                                </span>
                                                            </div>
                                                            C
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess1" id="assess14" value="D" <?php if($attend['assess1']=='D'){echo 'checked'; $assess[1]=65;} ?>  type="radio" onclick="window.assess[0]=65;avassess()">
                                                                </span>
                                                            </div>
                                                            D
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess1" id="assess15" value="E" <?php if($attend['assess1']=='E'){echo 'checked'; $assess[1]=55;} ?>  type="radio" onclick="window.assess[0] = 55;avassess()">
                                                                </span>
                                                            </div>
                                                            E
                                                        </label>

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">2.讲课由感染力,能吸引学生的注意力</label>
                                                <div class="col-md-9">
                                                    <div class="radio-list">
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess2" id="optionsRadios25" value="A" <?php if($attend['assess2']=='A'){echo 'checked'; $assess[2]=95;} ?>  type="radio"  onclick="window.assess[1] = 95;avassess()">
                                                                </span>
                                                            </div>
                                                            A
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess2" id="optionsRadios25" value="B" <?php if($attend['assess1']=='B'){echo 'checked'; $assess[2]=85;} ?>  type="radio" onclick="window.assess[1] = 85;avassess()">
                                                                </span>
                                                            </div>
                                                            B
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess2" id="optionsRadios25" value="C" <?php if($attend['assess2']=='C'){echo 'checked'; $assess[2]=75;} ?>  type="radio" onclick="window.assess[1] = 75;avassess()">
                                                                </span>
                                                            </div>
                                                            C
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess2" id="optionsRadios25" value="D" <?php if($attend['assess2']=='D'){echo 'checked'; $assess[2]=65;} ?>  type="radio" onclick="window.assess[1] = 65;avassess()">
                                                                </span>
                                                            </div>
                                                            D
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess2" id="optionsRadios25" value="E" <?php if($attend['assess2']=='E'){echo 'checked'; $assess[2]=55;} ?>  type="radio" onclick="window.assess[1] = 55;avassess()">
                                                                </span>
                                                            </div>
                                                            E
                                                        </label>

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">3.对问题的阐述深入浅出,有启发性</label>
                                                <div class="col-md-9">
                                                    <div class="radio-list">
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess3" id="optionsRadios25" value="A" <?php if($attend['assess3']=='A'){echo 'checked'; $assess[3]=95;} ?>  type="radio" onclick="window.assess[2] = 95;avassess()">
                                                                </span>
                                                            </div>
                                                            A
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess3" id="optionsRadios25" value="B" <?php if($attend['assess3']=='B'){echo 'checked'; $assess[3]=85;} ?>  type="radio" onclick="window.assess[2] = 85;avassess()">
                                                                </span>
                                                            </div>
                                                            B
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess3" id="optionsRadios25" value="C" <?php if($attend['assess3']=='C'){echo 'checked'; $assess[3]=75;} ?>  type="radio" onclick="window.assess[2] = 75;avassess()">
                                                                </span>
                                                            </div>
                                                            C
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess3" id="optionsRadios25" value="D" <?php if($attend['assess3']=='D'){echo 'checked'; $assess[3]=65;} ?>  type="radio" onclick="window.assess[2] = 65;avassess()">
                                                                </span>
                                                            </div>
                                                            D
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess3" id="optionsRadios25" value="E" <?php if($attend['assess3']=='E'){echo 'checked'; $assess[3]=55;} ?>  type="radio" onclick="window.assess[2] = 55;avassess()">
                                                                </span>
                                                            </div>
                                                            E
                                                        </label>

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">4.对问题的阐述简练准确,中带泥土书,思路清晰</label>
                                                <div class="col-md-9">
                                                    <div class="radio-list">
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess4" id="optionsRadios25" value="A" <?php if($attend['assess4']=='A'){echo 'checked'; $assess[4]=95;} ?>  type="radio" onclick="window.assess[3] = 95;avassess()">
                                                                </span>
                                                            </div>
                                                            A
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess4" id="optionsRadios25" value="B" <?php if($attend['assess4']=='B'){echo 'checked'; $assess[4]=85;} ?>  type="radio" onclick="window.assess[3] = 85;avassess()">
                                                                </span>
                                                            </div>
                                                            B
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess4" id="optionsRadios25" value="C" <?php if($attend['assess4']=='C'){echo 'checked'; $assess[4]=75;} ?>  type="radio" onclick="window.assess[3] = 75;avassess()">
                                                                </span>
                                                            </div>
                                                            C
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess4" id="optionsRadios25" value="D" <?php if($attend['assess4']=='D'){echo 'checked'; $assess[4]=65;} ?>  type="radio" onclick="window.assess[3] = 65;avassess()">
                                                                </span>
                                                            </div>
                                                            D
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess4" id="optionsRadios25" value="E" <?php if($attend['assess4']=='E'){echo 'checked'; $assess[4]=55;} ?>  type="radio" onclick="window.assess[3]=55;avassess()">
                                                                </span>
                                                            </div>
                                                            E
                                                        </label>

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">5.对课程内容娴熟,运用自如</label>
                                                <div class="col-md-9">
                                                    <div class="radio-list">
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess5" id="optionsRadios25" value="A" <?php if($attend['assess5']=='A'){echo 'checked'; $assess[5]=95;} ?>  type="radio" onclick="window.assess[4] = 95;avassess()">
                                                                </span>
                                                            </div>
                                                            A
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess5" id="optionsRadios25" value="B" <?php if($attend['assess5']=='B'){echo 'checked'; $assess[5]=85;} ?>  type="radio" onclick="window.assess[4] = 85;avassess()">
                                                                </span>
                                                            </div>
                                                            B
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess5" id="optionsRadios25" value="C" <?php if($attend['assess5']=='C'){echo 'checked'; $assess[5]=75;} ?>  type="radio" onclick="window.assess[4] = 75;avassess()">
                                                                </span>
                                                            </div>
                                                            C
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess5" id="optionsRadios25" value="D" <?php if($attend['assess5']=='D'){echo 'checked'; $assess[5]=65;} ?>  type="radio" onclick="window.assess[4] = 65;avassess()">
                                                                </span>
                                                            </div>
                                                            D
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess5" id="optionsRadios25" value="E" <?php if($attend['assess5']=='E'){echo 'checked'; $assess[5]=55;} ?>  type="radio" onclick="window.assess[4] = 55;avassess()">
                                                                </span>
                                                            </div>
                                                            E
                                                        </label>

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">6.讲课内容充实,信息量大</label>
                                                <div class="col-md-9">
                                                    <div class="radio-list">
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess6" id="optionsRadios25" value="A" <?php if($attend['assess6']=='A'){echo 'checked'; $assess[6]=95;} ?>  type="radio" onclick="window.assess[5] = 95;avassess()">
                                                                </span>
                                                            </div>
                                                            A
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess6" id="optionsRadios25" value="B" <?php if($attend['assess6']=='B'){echo 'checked'; $assess[6]=85;} ?>  type="radio" onclick="window.assess[5] = 85;avassess()">
                                                                </span>
                                                            </div>
                                                            B
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess6" id="optionsRadios25" value="C" <?php if($attend['assess6']=='C'){echo 'checked'; $assess[6]=75;} ?>  type="radio" onclick="window.assess[5] = 75;avassess()">
                                                                </span>
                                                            </div>
                                                            C
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess6" id="optionsRadios25" value="D" <?php if($attend['assess6']=='D'){echo 'checked'; $assess[6]=65;} ?>  type="radio" onclick="window.assess[5] = 65;avassess()">
                                                                </span>
                                                            </div>
                                                            D
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess6" id="optionsRadios25" value="E" <?php if($attend['assess6']=='E'){echo 'checked'; $assess[6]=55;} ?>  type="radio" onclick="window.assess[5] = 55;avassess()">
                                                                </span>
                                                            </div>
                                                            E
                                                        </label>

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">7.教学内容能反映或联系学科发展的新思想,性爱年,新成果</label>
                                                <div class="col-md-9">
                                                    <div class="radio-list">
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess7" id="optionsRadios25" value="A" <?php if($attend['assess7']=='A'){echo 'checked'; $assess[7]=95;} ?>  type="radio" onclick="window.assess[6] = 95;avassess()">
                                                                </span>
                                                            </div>
                                                            A
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess7" id="optionsRadios25" value="B" <?php if($attend['assess7']=='B'){echo 'checked'; $assess[7]=85;} ?>  type="radio" onclick="window.assess[6] = 85;avassess()">
                                                                </span>
                                                            </div>
                                                            B
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess7" id="optionsRadios25" value="C" <?php if($attend['assess7']=='C'){echo 'checked'; $assess[7]=75;} ?>  type="radio" onclick="window.assess[6] = 75;avassess()">
                                                                </span>
                                                            </div>
                                                            C
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess7" id="optionsRadios25" value="D" <?php if($attend['assess7']=='D'){echo 'checked'; $assess[7]=65;} ?>  type="radio" onclick="window.assess[6] = 65;avassess()">
                                                                </span>
                                                            </div>
                                                            D
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess7" id="optionsRadios25" value="E" <?php if($attend['assess7']=='E'){echo 'checked'; $assess[7]=55;} ?>  type="radio" onclick="window.assess[6] = 55;avassess()">
                                                                </span>
                                                            </div>
                                                            E
                                                        </label>

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">8.能给予学生思考,联想,创造的启迪</label>
                                                <div class="col-md-9">
                                                    <div class="radio-list">
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess8" id="optionsRadios25" value="A" <?php if($attend['assess8']=='A'){echo 'checked'; $assess[8]=95;} ?>  type="radio" onclick="window.assess[7] = 95;avassess()">
                                                                </span>
                                                            </div>
                                                            A
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess8" id="optionsRadios25" value="B" <?php if($attend['assess8']=='B'){echo 'checked'; $assess[8]=85;} ?>  type="radio" onclick="window.assess[7] = 85;avassess()">
                                                                </span>
                                                            </div>
                                                            B
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess8" id="optionsRadios25" value="C" <?php if($attend['assess8']=='C'){echo 'checked'; $assess[8]=75;} ?>  type="radio" onclick="window.assess[7] = 75;avassess()">
                                                                </span>
                                                            </div>
                                                            C
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess8" id="optionsRadios25" value="D" <?php if($attend['assess8']=='D'){echo 'checked'; $assess[8]=65;} ?>  type="radio" onclick="window.assess[7] = 65;avassess()">
                                                                </span>
                                                            </div>
                                                            D
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess8" id="optionsRadios25" value="E" <?php if($attend['assess8']=='E'){echo 'checked'; $assess[8]=55;} ?>  type="radio" onclick="window.assess[7] = 55;avassess()">
                                                                </span>
                                                            </div>
                                                            E
                                                        </label>

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">9.能调动学生情绪,课堂气氛活跃</label>
                                                <div class="col-md-9">
                                                    <div class="radio-list">
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess9" id="optionsRadios25" value="A" <?php if($attend['assess9']=='A'){echo 'checked'; $assess[9]=95;} ?>  type="radio" onclick="window.assess[8] = 95;avassess()">
                                                                </span>
                                                            </div>
                                                            A
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess9" id="optionsRadios25" value="B" <?php if($attend['assess9']=='B'){echo 'checked'; $assess[9]=85;} ?>  type="radio" onclick="window.assess[8] = 85;avassess()">
                                                                </span>
                                                            </div>
                                                            B
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess9" id="optionsRadios25" value="C" <?php if($attend['assess9']=='C'){echo 'checked'; $assess[9]=75;} ?>  type="radio" onclick="window.assess[8] = 75;avassess()">
                                                                </span>
                                                            </div>
                                                            C
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess9" id="optionsRadios25" value="D" <?php if($attend['assess9']=='D'){echo 'checked'; $assess[9]=65;} ?>  type="radio" onclick="window.assess[8] = 65;avassess()">
                                                                </span>
                                                            </div>
                                                            D
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess9" id="optionsRadios25" value="E" <?php if($attend['assess9']=='E'){echo 'checked'; $assess[9]=55;} ?>  type="radio" onclick="window.assess[8] = 55;avassess()">
                                                                </span>
                                                            </div>
                                                            E
                                                        </label>

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">10.能有效地利用教学媒体</label>
                                                <div class="col-md-9">
                                                    <div class="radio-list">
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess10" id="optionsRadios25" value="A" <?php if($attend['assess10']=='A'){echo 'checked'; $assess[10]=95;} ?>  type="radio" onclick="window.assess[9] = 95;avassess()">
                                                                </span>
                                                            </div>
                                                            A
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess10" id="optionsRadios25" value="B" <?php if($attend['assess10']=='B'){echo 'checked'; $assess[10]=85;} ?>  type="radio" onclick="window.assess[9] = 85;avassess()">
                                                                </span>
                                                            </div>
                                                            B
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess10" id="optionsRadios25" value="C" <?php if($attend['assess10']=='C'){echo 'checked'; $assess[10]=75;} ?>  type="radio" onclick="window.assess[9] = 75;avassess()">
                                                                </span>
                                                            </div>
                                                            C
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess10" id="optionsRadios25" value="D" <?php if($attend['assess10']=='D'){echo 'checked'; $assess[10]=65;} ?>  type="radio" onclick="window.assess[9] = 65;avassess()">
                                                                </span>
                                                            </div>
                                                            D
                                                        </label>
                                                        <label class="radio-inline">
                                                            <div id="uniform-optionsRadios25" class="radio">
                                                                <span>
                                                                    <input name="assess10" id="optionsRadios25" value="E" <?php if($attend['assess2']=='E'){echo 'checked'; $assess[10]=55;} ?>  type="radio" onclick="window.assess[9] = 55;avassess()">
                                                                </span>
                                                            </div>
                                                            E
                                                        </label>

                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">总评价等级</label>
                                                <div class="col-md-4">
                                                    <input id="assess" name="assess" class="form-control" value="<?php echo $attend['assess'] ?>" placeholder="0" readonly="" >
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-actions fluid">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="col-md-offset-4 col-md-2">
                                                <button type="submit" id="save" disabled class="btn blue button-next"> <i class="icon-save m-icon-white"></i> 保存</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END CONTAINER -->
    <!-- BEGIN FOOTER -->
    <div class="footer">
        <div class="footer-inner">
            2013 &copy; Metronic by keenthemes.
        </div>
        <div class="footer-tools">
                <span class="go-top">
                    <i class="icon-angle-up"></i>
                </span>
        </div>
    </div>
    <!-- END FOOTER -->
    <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
    <!-- BEGIN CORE PLUGINS -->
    <!--[if lt IE 9]>
    <script src="/assets/plugins/respond.min.js"></script>
    <script src="/assets/plugins/excanvas.min.js"></script>
    <![endif]-->
    <script src="/assets/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
    <!-- IMPORTANT! Load jquery-ui-1.10.3.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
    <script src="/assets/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js"
            type="text/javascript"></script>
    <script src="/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/jquery.cookie.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
    <!-- END CORE PLUGINS -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="/assets/plugins/jqvmap/jqvmap/jquery.vmap.js" type="text/javascript"></script>
    <script src="/assets/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js" type="text/javascript"></script>
    <script src="/assets/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js" type="text/javascript"></script>
    <script src="/assets/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js" type="text/javascript"></script>
    <script src="/assets/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js" type="text/javascript"></script>
    <script src="/assets/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js" type="text/javascript"></script>
    <script src="/assets/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js" type="text/javascript"></script>
    <script src="/assets/plugins/flot/jquery.flot.js" type="text/javascript"></script>
    <script src="/assets/plugins/flot/jquery.flot.resize.js" type="text/javascript"></script>
    <script src="/assets/plugins/jquery.pulsate.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/bootstrap-daterangepicker/moment.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>
    <!-- IMPORTANT! fullcalendar depends on jquery-ui-1.10.3.custom.min.js for drag & drop support -->
    <script src="/assets/plugins/fullcalendar/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.js" type="text/javascript"></script>
    <script src="/assets/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/assets/plugins/select2/select2.min.js"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="/assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
    <script type="text/javascript" src="/assets/plugins/jquery-validation/dist/additional-methods.min.js"></script>
    <script type="text/javascript" src="/assets/plugins/bootstrap-wizard/jquery.bootstrap.wizard.min.js"></script>
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="/assets/scripts/app.js" type="text/javascript"></script>
    <script src="/assets/scripts/index.js" type="text/javascript"></script>
    <script src="/assets/scripts/tasks.js" type="text/javascript"></script>
    <script src="/assets/scripts/form-wizard.js"></script>
    <!-- END PAGE LEVEL SCRIPTS -->
    <script src="/assets/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/bootstrap/js/bootstrap2-typeahead.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript" ></script>
    <script src="/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/jquery.cookie.min.js" type="text/javascript"></script>
    <script src="/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script>
    <!-- END CORE PLUGINS -->
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="/assets/plugins/fuelux/js/spinner.min.js"></script>
    <script type="text/javascript" src="/assets/plugins/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.js"></script>
    <script type="text/javascript" src="/assets/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="/assets/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>
    <script type="text/javascript" src="/assets/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
    <script type="text/javascript" src="/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript" src="/assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js"></script>
    <script type="text/javascript" src="/assets/plugins/clockface/js/clockface.js"></script>
    <script type="text/javascript" src="/assets/plugins/bootstrap-daterangepicker/moment.min.js"></script>
    <script type="text/javascript" src="/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
    <script type="text/javascript" src="/assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
    <script type="text/javascript" src="/assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>
    <script type="text/javascript" src="/assets/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js"></script>
    <script type="text/javascript" src="/assets/plugins/jquery.input-ip-address-control-1.0.min.js"></script>
    <script type="text/javascript" src="/assets/plugins/jquery-multi-select/js/jquery.multi-select.js"></script>
    <script type="text/javascript" src="/assets/plugins/jquery-multi-select/js/jquery.quicksearch.js"></script>
    <script src="/assets/plugins/jquery.pwstrength.bootstrap/src/pwstrength.js" type="text/javascript" ></script>
    <script src="/assets/plugins/bootstrap-switch/static/js/bootstrap-switch.min.js" type="text/javascript" ></script>
    <script src="/assets/plugins/jquery-tags-input/jquery.tagsinput.min.js" type="text/javascript" ></script>
    <script src="/assets/plugins/bootstrap-markdown/js/bootstrap-markdown.js" type="text/javascript" ></script>
    <script src="/assets/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" type="text/javascript" ></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="/assets/scripts/app.js"></script>
    <script src="/assets/scripts/form-components.js"></script>
    <script>
        window.assess = new Array;
        window.assess[0]=<?php echo $assess[1] ?>;
        window.assess[1]=<?php echo $assess[2] ?>;
        window.assess[2]=<?php echo $assess[3] ?>;
        window.assess[3]=<?php echo $assess[4] ?>;
        window.assess[4]=<?php echo $assess[5] ?>;
        window.assess[5]=<?php echo $assess[6] ?>;
        window.assess[6]=<?php echo $assess[7] ?>;
        window.assess[7]=<?php echo $assess[8] ?>;
        window.assess[8]=<?php echo $assess[9] ?>;
        window.assess[9]=<?php echo $assess[10] ?>;

        function avassess() {
            var mount=0;
            var flag=true;
            for(var i= 0;i<window.assess.length;i++) {
                mount += window.assess[i];
                if( window.assess[i]==0){
                    flag=false;
                }
            }
            if(flag){
                var av = mount/10;
                document.getElementById('assess').value = av;
                if(av==95||av==55){
                    alert("分享评价不可以全部为A或E");
                    document.getElementById('save').disabled=true;
                }
                else{
                    document.getElementById('save').disabled=false;
                }

            }

        }

        jQuery(document).ready(function () {

            App.init(); // initlayout and core plugins
            FormComponents.init();
            FormWizard.init();
            Index.init();
            Index.initJQVMAP(); // init index page's custom scripts
            Index.initCalendar(); // init index page's custom scripts
            Index.initCharts(); // init index page's custom scripts
            Index.initChat();
            Index.initMiniCharts();
            Index.initDashboardDaterange();
            Index.initIntro();
            Tasks.initDashboardWidget();
        });

    </script>
    <!-- END JAVASCRIPTS -->
    <script>
    </script>

</body>
<!-- END BODY -->
</html>